const properties = [
    {
        id: 1,
        name: "Modern Luxury Duplex",
        location: "Lekki, Lagos",
        price: "₦85,000,000",
        image: "images/property1.png",
        beds: "4 Beds",
        baths: "4 Baths",
        size: "450 m²",
        descriptionTitle: "A Home Designed for Modern Living",
        descriptionOne: "This beautiful modern duplex offers spacious living areas, stylish interiors and a comfortable environment for families looking for a premium home in Lekki.",
        descriptionTwo: "The property combines contemporary design with practical living spaces, making it ideal for both everyday family life and entertaining guests.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Private Parking",
            "✓ Secure Location",
            "✓ Ensuite Bedrooms",
            "✓ Outdoor Space"
        ],
        agentName: "David Okafor",
        agentRole: "Senior Property Consultant"
    },
    {
        id: 2,
        name: "Luxury City Apartment",
        location: "Ikoyi, Lagos",
        price: "₦12,000,000/year",
        image: "images/property2.png",
        beds: "3 Beds",
        baths: "3 Baths",
        size: "280 m²",
        descriptionTitle: "Luxury Living in the Heart of Ikoyi",
        descriptionOne: "This elegant apartment offers modern interiors, spacious rooms and a comfortable living environment in one of Lagos' most prestigious neighbourhoods.",
        descriptionTwo: "Designed for convenience and contemporary city living, the property provides easy access to business districts, restaurants and lifestyle destinations.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Area",
            "✓ Secure Parking",
            "✓ Ensuite Bedrooms",
            "✓ 24/7 Security",
            "✓ Prime Location"
        ],
        agentName: "Amaka Williams",
        agentRole: "Property Consultant"
    },
    {
        id: 3,
        name: "Contemporary Family Home",
        location: "Abuja, Nigeria",
        price: "₦120,000,000",
        image: "images/property3.png",
        beds: "5 Beds",
        baths: "5 Baths",
        size: "600 m²",
        descriptionTitle: "Spacious Comfort for the Whole Family",
        descriptionOne: "This contemporary family home combines generous living spaces with modern finishes, creating a comfortable environment for family living.",
        descriptionTwo: "With multiple bedrooms, spacious common areas and a well-planned layout, this home offers both privacy and room for entertaining.",
        features: [
            "✓ Modern Kitchen",
            "✓ Large Living Room",
            "✓ Private Parking",
            "✓ Ensuite Bedrooms",
            "✓ Spacious Compound",
            "✓ Secure Neighbourhood"
        ],
        agentName: "Daniel Okoro",
        agentRole: "Senior Property Consultant"
    },
    {
        id: 4,
        name: "Executive Waterfront Apartment",
        location: "Victoria Island, Lagos",
        price: "₦18,000,000/year",
        image: "images/property4.png",
        beds: "3 Beds",
        baths: "3 Baths",
        size: "320 m²",
        descriptionTitle: "Premium Waterfront City Living",
        descriptionOne: "This executive apartment offers stylish interiors and a premium waterfront lifestyle in the heart of Victoria Island.",
        descriptionTwo: "The spacious layout and excellent location make this property ideal for professionals and families seeking comfort and convenience.",
        features: [
            "✓ Waterfront Location",
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Ensuite Bedrooms",
            "✓ Secure Parking",
            "✓ 24/7 Security"
        ],
        agentName: "Sarah Adeyemi",
        agentRole: "Luxury Property Consultant"
    },
    {
        id: 5,
        name: "Spacious Family Residence",
        location: "Ikeja, Lagos",
        price: "₦65,000,000",
        image: "images/property5.png",
        beds: "4 Beds",
        baths: "4 Baths",
        size: "500 m²",
        descriptionTitle: "A Comfortable Family Residence",
        descriptionOne: "This spacious family residence provides generous rooms, comfortable living areas and a practical layout for everyday family life.",
        descriptionTwo: "Located in Ikeja, the property offers convenient access to major roads, businesses, schools and other essential amenities.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Private Parking",
            "✓ Ensuite Bedrooms",
            "✓ Large Compound",
            "✓ Secure Location"
        ],
        agentName: "Michael Johnson",
        agentRole: "Property Consultant"
    },
    {
        id: 6,
        name: "Modern City Apartment",
        location: "Wuse, Abuja",
        price: "₦9,500,000/year",
        image: "images/property6.png",
        beds: "2 Beds",
        baths: "2 Baths",
        size: "210 m²",
        descriptionTitle: "Modern Apartment in a Prime Location",
        descriptionOne: "This modern city apartment offers a stylish and comfortable living space in the popular Wuse district of Abuja.",
        descriptionTwo: "The property is well suited for professionals or small families looking for convenience, security and easy access to the city.",
        features: [
            "✓ Modern Kitchen",
            "✓ Open Living Area",
            "✓ Secure Parking",
            "✓ Ensuite Bedrooms",
            "✓ 24/7 Security",
            "✓ Prime Location"
        ],
        agentName: "Grace Ibrahim",
        agentRole: "Property Consultant"
    },
    {
        id: 7,
        name: "Contemporary Family Duplex",
        location: "Ajah, Lagos",
        price: "₦72,000,000",
        image: "images/property7.png",
        beds: "4 Beds",
        baths: "5 Baths",
        size: "420 m²",
        descriptionTitle: "Contemporary Design for Family Living",
        descriptionOne: "This contemporary duplex offers stylish interiors, spacious bedrooms and a comfortable layout designed for modern families.",
        descriptionTwo: "Located in Ajah, the property provides a balance of residential comfort and access to growing commercial and lifestyle destinations.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Outdoor Space",
            "✓ Secure Location"
        ],
        agentName: "David Okafor",
        agentRole: "Senior Property Consultant"
    },
    {
        id: 8,
        name: "Elegant Detached Home",
        location: "Gwarinpa, Abuja",
        price: "₦58,000,000",
        image: "images/property8.png",
        beds: "4 Beds",
        baths: "4 Baths",
        size: "480 m²",
        descriptionTitle: "Elegant and Spacious Detached Living",
        descriptionOne: "This detached home offers a peaceful residential setting with spacious interiors and a practical layout for comfortable family living.",
        descriptionTwo: "The property combines modern design with generous outdoor space, making it suitable for families seeking privacy and comfort.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Private Parking",
            "✓ Ensuite Bedrooms",
            "✓ Large Compound",
            "✓ Secure Neighbourhood"
        ],
        agentName: "Daniel Okoro",
        agentRole: "Property Consultant"
    },
    {
        id: 9,
        name: "Luxury Garden Duplex",
        location: "Port Harcourt, Rivers",
        price: "₦95,000,000",
        image: "images/property9.png",
        beds: "5 Beds",
        baths: "5 Baths",
        size: "550 m²",
        descriptionTitle: "Luxury Living with Beautiful Outdoor Space",
        descriptionOne: "This luxury duplex offers spacious interiors and a beautifully planned outdoor environment for comfortable family living.",
        descriptionTwo: "With generous bedrooms and entertaining spaces, the property is designed for families who value both style and functionality.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Private Garden",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Secure Location"
        ],
        agentName: "Amaka Williams",
        agentRole: "Senior Property Consultant"
    },
    {
        id: 10,
        name: "Modern Urban Apartment",
        location: "Yaba, Lagos",
        price: "₦6,500,000/year",
        image: "images/property10.png",
        beds: "2 Beds",
        baths: "2 Baths",
        size: "160 m²",
        descriptionTitle: "Smart Urban Living in Yaba",
        descriptionOne: "This modern apartment provides a comfortable and practical home in one of Lagos' vibrant urban districts.",
        descriptionTwo: "Its convenient location makes it ideal for professionals and young families looking for easy access to business, education and entertainment.",
        features: [
            "✓ Modern Kitchen",
            "✓ Comfortable Living Area",
            "✓ Secure Parking",
            "✓ Ensuite Bedrooms",
            "✓ 24/7 Security",
            "✓ Central Location"
        ],
        agentName: "Sarah Adeyemi",
        agentRole: "Property Consultant"
    },
    {
        id: 11,
        name: "Premium Contemporary Duplex",
        location: "Osapa, Lagos",
        price: "₦110,000,000",
        image: "images/property11.png",
        beds: "5 Beds",
        baths: "5 Baths",
        size: "600 m²",
        descriptionTitle: "Premium Contemporary Family Home",
        descriptionOne: "This premium duplex offers modern architecture, spacious interiors and high-quality living spaces designed for contemporary family life.",
        descriptionTwo: "The property provides generous bedrooms, entertaining areas and outdoor space in a desirable Lagos neighbourhood.",
        features: [
            "✓ Modern Kitchen",
            "✓ Large Living Room",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Outdoor Space",
            "✓ Secure Location"
        ],
        agentName: "Michael Johnson",
        agentRole: "Senior Property Consultant"
    },
    {
        id: 12,
        name: "Luxury Executive Residence",
        location: "Maitama, Abuja",
        price: "₦185,000,000",
        image: "images/property12.png",
        beds: "6 Beds",
        baths: "6 Baths",
        size: "720 m²",
        descriptionTitle: "Exceptional Executive Living",
        descriptionOne: "This luxury executive residence offers expansive living spaces, premium finishes and an impressive layout in the prestigious Maitama district.",
        descriptionTwo: "Designed for refined family living and entertaining, the property combines comfort, privacy and modern elegance.",
        features: [
            "✓ Premium Kitchen",
            "✓ Multiple Living Areas",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Spacious Compound",
            "✓ Secure Location"
        ],
        agentName: "Grace Ibrahim",
        agentRole: "Luxury Property Consultant"
    },
    {
        id: 13,
        name: "Residential Land Plot",
        location: "Lekki, Lagos",
        price: "₦45,000,000",
        image: "images/property13.png",
        beds: "Residential",
        baths: "Dry Land",
        size: "600 m²",
        descriptionTitle: "A Prime Residential Land Opportunity",
        descriptionOne: "This residential land plot offers an excellent opportunity to build a private home in a desirable area of Lekki.",
        descriptionTwo: "The dry land provides a suitable foundation for future development and is positioned in a growing residential environment.",
        features: [
            "✓ 600 m² Plot",
            "✓ Residential Use",
            "✓ Dry Land",
            "✓ Prime Location",
            "✓ Development Opportunity",
            "✓ Secure Neighbourhood"
        ],
        agentName: "David Okafor",
        agentRole: "Land & Property Consultant"
    },
    {
        id: 14,
        name: "Spacious Family Home",
        location: "Rumuola, Port Harcourt",
        price: "₦75,000,000",
        image: "images/property14.png",
        beds: "4 Beds",
        baths: "4 Baths",
        size: "520 m²",
        descriptionTitle: "Spacious Home for Comfortable Family Living",
        descriptionOne: "This family home provides spacious interiors, comfortable bedrooms and a practical layout suited to everyday family living.",
        descriptionTwo: "The property offers generous outdoor space and convenient access to essential amenities in Rumuola.",
        features: [
            "✓ Modern Kitchen",
            "✓ Spacious Living Room",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Large Compound",
            "✓ Secure Location"
        ],
        agentName: "Daniel Okoro",
        agentRole: "Property Consultant"
    },
    {
        id: 15,
        name: "Premium Island Residence",
        location: "Banana Island, Lagos",
        price: "₦220,000,000",
        image: "images/property15.png",
        beds: "4 Beds",
        baths: "5 Baths",
        size: "480 m²",
        descriptionTitle: "Premium Island Living",
        descriptionOne: "This premium residence offers an exceptional combination of contemporary design, spacious interiors and an exclusive Banana Island location.",
        descriptionTwo: "The property is designed for residents seeking privacy, comfort and a sophisticated lifestyle in one of Lagos' most prestigious communities.",
        features: [
            "✓ Premium Kitchen",
            "✓ Spacious Living Areas",
            "✓ Ensuite Bedrooms",
            "✓ Private Parking",
            "✓ Luxury Finishes",
            "✓ Secure Location"
        ],
        agentName: "Sarah Adeyemi",
        agentRole: "Luxury Property Consultant"
    }
];